 compania: {type: Schema.ObjectId, ref: 'compania'}, 
    tipo_cliente: {type: Schema.ObjectId, ref: 'tipo_cliente', required: true}, 
    nombre: {type: String, required: true},
    vendedor: {type: Schema.ObjectId, ref: 'usuario', required: false},
    tipo_documento: {type: Schema.ObjectId, ref: 'tipo_documento', required: true},
    documento: {type: String, required: false},
    pagina_web: {type: String, required: false},  
    email: {type: String, required: false}, 
    telefono: {type: String, required: false},
    telefono1: {type: String, required: false},
    fax: {type: String, required: false},
    moneda_curso: {type: Schema.ObjectId, ref: 'moneda', required: true},
    termino_pago: {type: Schema.ObjectId, ref: 'termino_pago', required: true},
    limite_credito: {type: Number, required: true},
    estatus: {type: Boolean, required: true},  
    createdAt: {type: Date, default: Date.now, require:true},
